baseURL = "https://starcoinorg.github.io"
languageCode = "en"
title = "Starcoin"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "book"

[languages]
  [languages.en]
    languageName = "English"
    weight = 10
  [languages.zh]
    languageName = "Chinese"
    weight = 20
