baseURL = "https://starcoinorg.github.io"
languageCode = "en"
title = "Starcoin"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 10
  [languages.zh]
    contentDir = "content/zh"
    languageName = "Chinese"
    weight = 20
